### ISSUE TITLE
Paper related with this repo

### ISSUE THREAD

**Issue by braveheartwithlove** [asvspoof/D3M#5]
@DeeDive Do you have any paper submission associated with this work?

Thanks

**Comment by Soar-Sir** [comment]
I also want to ask same question. Thanks a lot!

**Comment by DeeDiveT** [comment]
Hi @braveheartwithlove and @Soar-Sir, thanks for your interest in this work. Paper submission associated with this work is currently under review and it will be publicly available asap.

**Comment by DeeDive** [comment]
Hi @braveheartwithlove and @Soar-Sir, thanks for your interest in this work.
Paper submission associated with this work is currently under review and it will be made publicly available asap.

**Comment by DeeDive** [comment]
Hi @Soar-Sir @braveheartwithlove , I have updated the repository just now with the associated paper. Feel free to ask if you have further issues.
