### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by kylepob** [asvspoof/D3M#6]
Hello, thank you for this work! Would you happen to have the pre-trained model available?

**Comment by DeeDive** [comment]
Hi @kylepob, thanks for your interest in our work. We indeed saved the pretrained models and it needs some time to arrange and reorganize them. If possible, we will release them together with the associated paper as soon as possible.

Best regards

**Comment by kylepob** [comment]
Much appreciated! Thank you, and stay safe!
